// Catalog Data — edit this file to add/remove products and sections
// Also update data.json if you need the pure JSON version
window.catalogData = {
  "sections": [
    {
      "id": "perogies",
      "titleKey": "section-perogies-title",
      "navLabelKey": "cat-perogies",
      "icon": "🥟",
      "scrollMargin": "scroll-mt-40",
      "products": [
        {
          "id": "p1",
          "name": "Siberian (Beef & Pork) — Hand Made",
          "descriptionKey": "p1-desc",
          "price": 12.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-meat-handmade",
          "dietary": { "veg": false, "df": true, "pf": false },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p1-ingredients" },
          "nutrition": { "calories": 340, "protein": "16g", "carbs": "40g" },
          "cookingKey": "p1-cook"
        },
        {
          "id": "p2",
          "name": "Chicken (Chicken Breast) — Hand Made",
          "descriptionKey": "p2-desc",
          "price": 12.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-meat-handmade",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p2-ingredients" },
          "nutrition": { "calories": 320, "protein": "20g", "carbs": "38g" },
          "cookingKey": "p2-cook"
        },
        {
          "id": "p3",
          "name": "Veal — Hand Made",
          "descriptionKey": "p3-desc",
          "price": 12.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-meat-handmade",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p3-ingredients" },
          "nutrition": { "calories": 330, "protein": "18g", "carbs": "39g" },
          "cookingKey": "p3-cook"
        },
        {
          "id": "p4",
          "name": "Turkey — Hand Made",
          "descriptionKey": "p4-desc",
          "price": 12.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-meat-handmade",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p4-ingredients" },
          "nutrition": { "calories": 300, "protein": "19g", "carbs": "38g" },
          "cookingKey": "p4-cook"
        },
        {
          "id": "p5",
          "name": "Siberian (Beef & Pork) — Machine Made",
          "descriptionKey": "p5-desc",
          "price": 10.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-meat-machine",
          "dietary": { "veg": false, "df": true, "pf": false },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p5-ingredients" },
          "nutrition": { "calories": 340, "protein": "16g", "carbs": "40g" },
          "cookingKey": "p5-cook"
        },
        {
          "id": "p6",
          "name": "Chicken (Chicken Breast) — Machine Made",
          "descriptionKey": "p6-desc",
          "price": 10.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-meat-machine",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p6-ingredients" },
          "nutrition": { "calories": 320, "protein": "20g", "carbs": "38g" },
          "cookingKey": "p6-cook"
        },
        {
          "id": "p7",
          "name": "Veal — Machine Made",
          "descriptionKey": "p7-desc",
          "price": 10.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-meat-machine",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p7-ingredients" },
          "nutrition": { "calories": 330, "protein": "18g", "carbs": "39g" },
          "cookingKey": "p7-cook"
        },
        {
          "id": "p8",
          "name": "Turkey — Machine Made",
          "descriptionKey": "p8-desc",
          "price": 10.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-meat-machine",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p8-ingredients" },
          "nutrition": { "calories": 300, "protein": "19g", "carbs": "38g" },
          "cookingKey": "p8-cook"
        },
        {
          "id": "p9",
          "name": "Lamb",
          "descriptionKey": "p9-desc",
          "price": 12.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-meat-machine",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p9-ingredients" },
          "nutrition": { "calories": 360, "protein": "18g", "carbs": "40g" },
          "cookingKey": "p9-cook"
        },
        {
          "id": "p10",
          "name": "Meat Perogies",
          "descriptionKey": "p10-desc",
          "price": 12.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-meat-machine",
          "dietary": { "veg": false, "df": true, "pf": false },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p10-ingredients" },
          "nutrition": { "calories": 350, "protein": "16g", "carbs": "41g" },
          "cookingKey": "p10-cook"
        },
        {
          "id": "p11",
          "name": "Potato & Fried Onions",
          "descriptionKey": "p11-desc",
          "price": 9.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-potato",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p11-ingredients" },
          "nutrition": { "calories": 290, "protein": "8g", "carbs": "46g" },
          "cookingKey": "p11-cook"
        },
        {
          "id": "p12",
          "name": "Potato & Mushrooms",
          "descriptionKey": "p12-desc",
          "price": 9.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-potato",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p12-ingredients" },
          "nutrition": { "calories": 280, "protein": "8g", "carbs": "45g" },
          "cookingKey": "p12-cook"
        },
        {
          "id": "p13",
          "name": "Potato & Bacon",
          "descriptionKey": "p13-desc",
          "price": 9.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-potato",
          "dietary": { "veg": false, "df": false, "pf": false },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p13-ingredients" },
          "nutrition": { "calories": 320, "protein": "10g", "carbs": "44g" },
          "cookingKey": "p13-cook"
        },
        {
          "id": "p14",
          "name": "Potato & Cheddar",
          "descriptionKey": "p14-desc",
          "price": 9.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-potato",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p14-ingredients" },
          "nutrition": { "calories": 300, "protein": "9g", "carbs": "45g" },
          "cookingKey": "p14-cook"
        },
        {
          "id": "p15",
          "name": "Potato, Cheddar & Onions",
          "descriptionKey": "p15-desc",
          "price": 9.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-potato",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p15-ingredients" },
          "nutrition": { "calories": 305, "protein": "9g", "carbs": "45g" },
          "cookingKey": "p15-cook"
        },
        {
          "id": "p16",
          "name": "Potato, Cheddar & Jalapeno",
          "descriptionKey": "p16-desc",
          "price": 9.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-potato",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p16-ingredients" },
          "nutrition": { "calories": 305, "protein": "9g", "carbs": "45g" },
          "cookingKey": "p16-cook"
        },
        {
          "id": "p17",
          "name": "Potato & Cottage Cheese",
          "descriptionKey": "p17-desc",
          "price": 9.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-potato",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p17-ingredients" },
          "nutrition": { "calories": 290, "protein": "10g", "carbs": "44g" },
          "cookingKey": "p17-cook"
        },
        {
          "id": "p18",
          "name": "Potato, Spinach & Feta",
          "descriptionKey": "p18-desc",
          "price": 9.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-potato",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p18-ingredients" },
          "nutrition": { "calories": 295, "protein": "10g", "carbs": "43g" },
          "cookingKey": "p18-cook"
        },
        {
          "id": "p19",
          "name": "Potato & Beef Brisket",
          "descriptionKey": "p19-desc",
          "price": 9.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-potato",
          "dietary": { "veg": false, "df": false, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p19-ingredients" },
          "nutrition": { "calories": 330, "protein": "14g", "carbs": "42g" },
          "cookingKey": "p19-cook"
        },
        {
          "id": "p20",
          "name": "Sweet Cottage Cheese",
          "descriptionKey": "p20-desc",
          "price": 10.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-dessert",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p20-ingredients" },
          "nutrition": { "calories": 280, "protein": "9g", "carbs": "46g" },
          "cookingKey": "p20-cook"
        },
        {
          "id": "p21",
          "name": "Cottage Cheese (No Sugar)",
          "descriptionKey": "p21-desc",
          "price": 10.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-dessert",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p21-ingredients" },
          "nutrition": { "calories": 260, "protein": "10g", "carbs": "42g" },
          "cookingKey": "p21-cook"
        },
        {
          "id": "p22",
          "name": "Cherry",
          "descriptionKey": "p22-desc",
          "price": 10.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-dessert",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p22-ingredients" },
          "nutrition": { "calories": 250, "protein": "4g", "carbs": "52g" },
          "cookingKey": "p22-cook"
        },
        {
          "id": "p23",
          "name": "Blueberry",
          "descriptionKey": "p23-desc",
          "price": 10.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-dessert",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p23-ingredients" },
          "nutrition": { "calories": 255, "protein": "4g", "carbs": "53g" },
          "cookingKey": "p23-cook"
        },
        {
          "id": "p24",
          "name": "Strawberry",
          "descriptionKey": "p24-desc",
          "price": 10.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-dessert",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p24-ingredients" },
          "nutrition": { "calories": 250, "protein": "4g", "carbs": "52g" },
          "cookingKey": "p24-cook"
        },
        {
          "id": "p25",
          "name": "Apple Cinnamon",
          "descriptionKey": "p25-desc",
          "price": 9.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-dessert",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p25-ingredients" },
          "nutrition": { "calories": 260, "protein": "4g", "carbs": "54g" },
          "cookingKey": "p25-cook"
        },
        {
          "id": "p26",
          "name": "Sauerkraut",
          "descriptionKey": "p26-desc",
          "price": 9.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-other",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p26-ingredients" },
          "nutrition": { "calories": 230, "protein": "5g", "carbs": "42g" },
          "cookingKey": "p26-cook"
        },
        {
          "id": "p27",
          "name": "Sauerkraut & Mushroom",
          "descriptionKey": "p27-desc",
          "price": 9.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-other",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p27-ingredients" },
          "nutrition": { "calories": 235, "protein": "5g", "carbs": "41g" },
          "cookingKey": "p27-cook"
        },
        {
          "id": "p28",
          "name": "Mushroom",
          "descriptionKey": "p28-desc",
          "price": 12.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-other",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p28-ingredients" },
          "nutrition": { "calories": 250, "protein": "7g", "carbs": "40g" },
          "cookingKey": "p28-cook"
        },
        {
          "id": "p29",
          "name": "Kasha & Mushroom",
          "descriptionKey": "p29-desc",
          "price": 9.00,
          "unitKey": "900g-bag",
          "subgroup": "subgroup-other",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "p29-ingredients" },
          "nutrition": { "calories": 255, "protein": "7g", "carbs": "42g" },
          "cookingKey": "p29-cook"
        }
      ]
    },
    {
      "id": "classics",
      "titleKey": "section-classics-title",
      "navLabelKey": "cat-classics",
      "icon": "🥩",
      "scrollMargin": "scroll-mt-40",
      "products": [
        {
          "id": "c1",
          "name": "Manti (Beef & Pork)",
          "descriptionKey": "c1-desc",
          "price": 20.00,
          "unitKey": "per-6pcs",
          "subgroup": "subgroup-manti-khinkali",
          "dietary": { "veg": false, "df": true, "pf": false },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "c1-ingredients" },
          "nutrition": { "calories": 280, "protein": "15g", "carbs": "30g" },
          "cookingKey": "c1-cook"
        },
        {
          "id": "c2",
          "name": "Khinkali (Beef & Pork)",
          "descriptionKey": "c2-desc",
          "price": 22.00,
          "unitKey": "per-6pcs",
          "subgroup": "subgroup-manti-khinkali",
          "dietary": { "veg": false, "df": true, "pf": false },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "c2-ingredients" },
          "nutrition": { "calories": 300, "protein": "16g", "carbs": "32g" },
          "cookingKey": "c2-cook"
        },
        {
          "id": "c3",
          "name": "Cabbage Rolls (Beef & Pork)",
          "descriptionKey": "c3-desc",
          "price": 20.00,
          "unitKey": "per-6pcs",
          "subgroup": "subgroup-cabbage-rolls",
          "dietary": { "veg": false, "df": true, "pf": false },
          "image": "images/golubtsi.jpg",
          "about": { "ingredientsKey": "c3-ingredients" },
          "nutrition": { "calories": 220, "protein": "14g", "carbs": "20g" },
          "cookingKey": "c3-cook"
        },
        {
          "id": "c4",
          "name": "Cabbage Rolls (Veal)",
          "descriptionKey": "c4-desc",
          "price": 20.00,
          "unitKey": "per-6pcs",
          "subgroup": "subgroup-cabbage-rolls",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/golubtsi.jpg",
          "about": { "ingredientsKey": "c4-ingredients" },
          "nutrition": { "calories": 210, "protein": "15g", "carbs": "18g" },
          "cookingKey": "c4-cook"
        },
        {
          "id": "c5",
          "name": "Cabbage Rolls (Chicken)",
          "descriptionKey": "c5-desc",
          "price": 20.00,
          "unitKey": "per-6pcs",
          "subgroup": "subgroup-cabbage-rolls",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/golubtsi.jpg",
          "about": { "ingredientsKey": "c5-ingredients" },
          "nutrition": { "calories": 190, "protein": "16g", "carbs": "16g" },
          "cookingKey": "c5-cook"
        },
        {
          "id": "c6",
          "name": "Cabbage Rolls (Vegetable)",
          "descriptionKey": "c6-desc",
          "price": 20.00,
          "unitKey": "per-6pcs",
          "subgroup": "subgroup-cabbage-rolls",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/golubtsi.jpg",
          "about": { "ingredientsKey": "c6-ingredients" },
          "nutrition": { "calories": 160, "protein": "6g", "carbs": "26g" },
          "cookingKey": "c6-cook"
        },
        {
          "id": "c7",
          "name": "Chebureki (Chicken)",
          "descriptionKey": "c7-desc",
          "price": 20.00,
          "unitKey": "per-10pcs",
          "subgroup": "subgroup-chebureki",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/cheburiki.jpg",
          "about": { "ingredientsKey": "c7-ingredients" },
          "nutrition": { "calories": 340, "protein": "17g", "carbs": "30g" },
          "cookingKey": "c7-cook"
        },
        {
          "id": "c8",
          "name": "Chebureki (Beef & Pork)",
          "descriptionKey": "c8-desc",
          "price": 20.00,
          "unitKey": "per-10pcs",
          "subgroup": "subgroup-chebureki",
          "dietary": { "veg": false, "df": true, "pf": false },
          "image": "images/cheburiki.jpg",
          "about": { "ingredientsKey": "c8-ingredients" },
          "nutrition": { "calories": 380, "protein": "18g", "carbs": "32g" },
          "cookingKey": "c8-cook"
        },
        {
          "id": "c9",
          "name": "Chebureki (Veal)",
          "descriptionKey": "c9-desc",
          "price": 20.00,
          "unitKey": "per-10pcs",
          "subgroup": "subgroup-chebureki",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/cheburiki.jpg",
          "about": { "ingredientsKey": "c9-ingredients" },
          "nutrition": { "calories": 360, "protein": "19g", "carbs": "31g" },
          "cookingKey": "c9-cook"
        },
        {
          "id": "c10",
          "name": "Chebureki (Lamb)",
          "descriptionKey": "c10-desc",
          "price": 22.00,
          "unitKey": "per-10pcs",
          "subgroup": "subgroup-chebureki",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/cheburiki.jpg",
          "about": { "ingredientsKey": "c10-ingredients" },
          "nutrition": { "calories": 400, "protein": "18g", "carbs": "32g" },
          "cookingKey": "c10-cook"
        },
        {
          "id": "c11",
          "name": "Kotlete — Chicken (Raw)",
          "descriptionKey": "c11-desc",
          "price": 12.00,
          "unitKey": "per-6pcs",
          "subgroup": "subgroup-kotlete",
          "dietary": { "veg": false, "df": false, "pf": true },
          "image": "images/cheburiki.jpg",
          "about": { "ingredientsKey": "c11-ingredients" },
          "nutrition": { "calories": 250, "protein": "24g", "carbs": "6g" },
          "cookingKey": "c11-cook"
        },
        {
          "id": "c12",
          "name": "Kotlete — Chicken (Fried)",
          "descriptionKey": "c12-desc",
          "price": 15.00,
          "unitKey": "per-6pcs",
          "subgroup": "subgroup-kotlete",
          "dietary": { "veg": false, "df": false, "pf": true },
          "image": "images/cheburiki.jpg",
          "about": { "ingredientsKey": "c12-ingredients" },
          "nutrition": { "calories": 290, "protein": "24g", "carbs": "8g" },
          "cookingKey": "c12-cook"
        },
        {
          "id": "c13",
          "name": "Pirozhki — Beef & Pork",
          "descriptionKey": "c13-desc",
          "price": 20.00,
          "unitKey": "per-10pcs",
          "subgroup": "subgroup-pirozhki",
          "dietary": { "veg": false, "df": true, "pf": false },
          "image": "images/cheburiki.jpg",
          "about": { "ingredientsKey": "c13-ingredients" },
          "nutrition": { "calories": 310, "protein": "12g", "carbs": "38g" },
          "cookingKey": "c13-cook"
        },
        {
          "id": "c14",
          "name": "Pirozhki — Beef & Chicken",
          "descriptionKey": "c14-desc",
          "price": 20.00,
          "unitKey": "per-10pcs",
          "subgroup": "subgroup-pirozhki",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/cheburiki.jpg",
          "about": { "ingredientsKey": "c14-ingredients" },
          "nutrition": { "calories": 300, "protein": "13g", "carbs": "36g" },
          "cookingKey": "c14-cook"
        },
        {
          "id": "c15",
          "name": "Pirozhki — Cabbage",
          "descriptionKey": "c15-desc",
          "price": 18.00,
          "unitKey": "per-10pcs",
          "subgroup": "subgroup-pirozhki",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/cheburiki.jpg",
          "about": { "ingredientsKey": "c15-ingredients" },
          "nutrition": { "calories": 260, "protein": "6g", "carbs": "42g" },
          "cookingKey": "c15-cook"
        },
        {
          "id": "c16",
          "name": "Pirozhki — Potato",
          "descriptionKey": "c16-desc",
          "price": 16.00,
          "unitKey": "per-10pcs",
          "subgroup": "subgroup-pirozhki",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/cheburiki.jpg",
          "about": { "ingredientsKey": "c16-ingredients" },
          "nutrition": { "calories": 270, "protein": "6g", "carbs": "43g" },
          "cookingKey": "c16-cook"
        },
        {
          "id": "c17",
          "name": "Pampushki with Garlic",
          "descriptionKey": "c17-desc",
          "price": 16.00,
          "unitKey": "per-10pcs",
          "subgroup": "subgroup-pirozhki",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/cheburiki.jpg",
          "about": { "ingredientsKey": "c17-ingredients" },
          "nutrition": { "calories": 220, "protein": "5g", "carbs": "36g" },
          "cookingKey": "c17-cook"
        },
        {
          "id": "c18",
          "name": "Savoury Crepes — Plain",
          "descriptionKey": "c18-desc",
          "price": 10.00,
          "unitKey": "per-8pc",
          "subgroup": "subgroup-savoury-crepes",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/golubtsi.jpg",
          "about": { "ingredientsKey": "c18-ingredients" },
          "nutrition": { "calories": 180, "protein": "6g", "carbs": "22g" },
          "cookingKey": "c18-cook"
        },
        {
          "id": "c19",
          "name": "Savoury Crepes — Chicken",
          "descriptionKey": "c19-desc",
          "price": 10.00,
          "unitKey": "per-8pc",
          "subgroup": "subgroup-savoury-crepes",
          "dietary": { "veg": false, "df": false, "pf": true },
          "image": "images/golubtsi.jpg",
          "about": { "ingredientsKey": "c19-ingredients" },
          "nutrition": { "calories": 240, "protein": "16g", "carbs": "20g" },
          "cookingKey": "c19-cook"
        },
        {
          "id": "c20",
          "name": "Savoury Crepes — Cheese & Salmon",
          "descriptionKey": "c20-desc",
          "price": 10.00,
          "unitKey": "per-8pc",
          "subgroup": "subgroup-savoury-crepes",
          "dietary": { "veg": false, "df": false, "pf": true },
          "image": "images/golubtsi.jpg",
          "about": { "ingredientsKey": "c20-ingredients" },
          "nutrition": { "calories": 260, "protein": "14g", "carbs": "20g" },
          "cookingKey": "c20-cook"
        },
        {
          "id": "c21",
          "name": "Savoury Crepes — Chicken & Mushroom",
          "descriptionKey": "c21-desc",
          "price": 10.00,
          "unitKey": "per-8pc",
          "subgroup": "subgroup-savoury-crepes",
          "dietary": { "veg": false, "df": false, "pf": true },
          "image": "images/golubtsi.jpg",
          "about": { "ingredientsKey": "c21-ingredients" },
          "nutrition": { "calories": 250, "protein": "15g", "carbs": "19g" },
          "cookingKey": "c21-cook"
        },
        {
          "id": "c22",
          "name": "Savoury Crepes — Cabbage & Mushroom",
          "descriptionKey": "c22-desc",
          "price": 10.00,
          "unitKey": "per-8pc",
          "subgroup": "subgroup-savoury-crepes",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/golubtsi.jpg",
          "about": { "ingredientsKey": "c22-ingredients" },
          "nutrition": { "calories": 220, "protein": "8g", "carbs": "26g" },
          "cookingKey": "c22-cook"
        },
        {
          "id": "c23",
          "name": "Savoury Crepes — Egg & Green Onion",
          "descriptionKey": "c23-desc",
          "price": 10.00,
          "unitKey": "per-8pc",
          "subgroup": "subgroup-savoury-crepes",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/golubtsi.jpg",
          "about": { "ingredientsKey": "c23-ingredients" },
          "nutrition": { "calories": 210, "protein": "9g", "carbs": "20g" },
          "cookingKey": "c23-cook"
        },
        {
          "id": "c24",
          "name": "Dessert Crepes — Cherry",
          "descriptionKey": "c24-desc",
          "price": 10.00,
          "unitKey": "per-8pc",
          "subgroup": "subgroup-dessert-crepes",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "c24-ingredients" },
          "nutrition": { "calories": 230, "protein": "5g", "carbs": "34g" },
          "cookingKey": "c24-cook"
        },
        {
          "id": "c25",
          "name": "Dessert Crepes — Cottage Cheese",
          "descriptionKey": "c25-desc",
          "price": 10.00,
          "unitKey": "per-8pc",
          "subgroup": "subgroup-dessert-crepes",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "c25-ingredients" },
          "nutrition": { "calories": 240, "protein": "11g", "carbs": "30g" },
          "cookingKey": "c25-cook"
        },
        {
          "id": "c26",
          "name": "Dessert Crepes — Cottage Cheese & Raspberry",
          "descriptionKey": "c26-desc",
          "price": 10.00,
          "unitKey": "per-8pc",
          "subgroup": "subgroup-dessert-crepes",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "c26-ingredients" },
          "nutrition": { "calories": 240, "protein": "10g", "carbs": "32g" },
          "cookingKey": "c26-cook"
        },
        {
          "id": "c27",
          "name": "Dessert Crepes — Apple",
          "descriptionKey": "c27-desc",
          "price": 10.00,
          "unitKey": "per-8pc",
          "subgroup": "subgroup-dessert-crepes",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "c27-ingredients" },
          "nutrition": { "calories": 220, "protein": "5g", "carbs": "32g" },
          "cookingKey": "c27-cook"
        },
        {
          "id": "c28",
          "name": "Dessert Crepes — Pear",
          "descriptionKey": "c28-desc",
          "price": 10.00,
          "unitKey": "per-8pc",
          "subgroup": "subgroup-dessert-crepes",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "c28-ingredients" },
          "nutrition": { "calories": 220, "protein": "5g", "carbs": "32g" },
          "cookingKey": "c28-cook"
        },
        {
          "id": "c29",
          "name": "Dessert Crepes — Plum",
          "descriptionKey": "c29-desc",
          "price": 10.00,
          "unitKey": "per-8pc",
          "subgroup": "subgroup-dessert-crepes",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "c29-ingredients" },
          "nutrition": { "calories": 220, "protein": "5g", "carbs": "32g" },
          "cookingKey": "c29-cook"
        },
        {
          "id": "c30",
          "name": "Dessert Crepes — Poppy Seed",
          "descriptionKey": "c30-desc",
          "price": 10.00,
          "unitKey": "per-8pc",
          "subgroup": "subgroup-dessert-crepes",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "c30-ingredients" },
          "nutrition": { "calories": 250, "protein": "7g", "carbs": "30g" },
          "cookingKey": "c30-cook"
        },
        {
          "id": "c31",
          "name": "Cheese Pancakes (Syrniki)",
          "descriptionKey": "c31-desc",
          "price": 6.00,
          "subgroup": "subgroup-main-courses",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/beefStroganoff.jpg",
          "about": { "ingredientsKey": "c31-ingredients" },
          "nutrition": { "calories": 190, "protein": "10g", "carbs": "18g" },
          "cookingKey": "c31-cook"
        },
        {
          "id": "c32",
          "name": "Khachapuri Ajarski",
          "descriptionKey": "c32-desc",
          "price": 14.00,
          "subgroup": "subgroup-main-courses",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/beefStroganoff.jpg",
          "about": { "ingredientsKey": "c32-ingredients" },
          "nutrition": { "calories": 420, "protein": "20g", "carbs": "38g" },
          "cookingKey": "c32-cook"
        },
        {
          "id": "c33",
          "name": "Belyashi",
          "descriptionKey": "c33-desc",
          "price": 6.00,
          "subgroup": "subgroup-main-courses",
          "dietary": { "veg": false, "df": true, "pf": false },
          "image": "images/beefStroganoff.jpg",
          "about": { "ingredientsKey": "c33-ingredients" },
          "nutrition": { "calories": 350, "protein": "14g", "carbs": "30g" },
          "cookingKey": "c33-cook"
        },
        {
          "id": "c34",
          "name": "Samsa",
          "descriptionKey": "c34-desc",
          "price": 12.00,
          "subgroup": "subgroup-main-courses",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/beefStroganoff.jpg",
          "about": { "ingredientsKey": "c34-ingredients" },
          "nutrition": { "calories": 380, "protein": "15g", "carbs": "34g" },
          "cookingKey": "c34-cook"
        },
        {
          "id": "c35",
          "name": "Lula Kebab",
          "descriptionKey": "c35-desc",
          "price": 14.00,
          "subgroup": "subgroup-main-courses",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/beefStroganoff.jpg",
          "about": { "ingredientsKey": "c35-ingredients" },
          "nutrition": { "calories": 320, "protein": "24g", "carbs": "6g" },
          "cookingKey": "c35-cook"
        },
        {
          "id": "c36",
          "name": "Mititei",
          "descriptionKey": "c36-desc",
          "price": 14.00,
          "subgroup": "subgroup-main-courses",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/beefStroganoff.jpg",
          "about": { "ingredientsKey": "c36-ingredients" },
          "nutrition": { "calories": 310, "protein": "22g", "carbs": "5g" },
          "cookingKey": "c36-cook"
        },
        {
          "id": "c37",
          "name": "Chicken Meatballs (1 kg)",
          "descriptionKey": "c37-desc",
          "price": 12.00,
          "subgroup": "subgroup-main-courses",
          "dietary": { "veg": false, "df": false, "pf": true },
          "image": "images/beefStroganoff.jpg",
          "about": { "ingredientsKey": "c37-ingredients" },
          "nutrition": { "calories": 220, "protein": "20g", "carbs": "6g" },
          "cookingKey": "c37-cook"
        },
        {
          "id": "c38",
          "name": "Maina (Jewish Wedding Pie)",
          "descriptionKey": "c38-desc",
          "price": 12.00,
          "subgroup": "subgroup-main-courses",
          "dietary": { "veg": false, "df": false, "pf": true },
          "image": "images/beefStroganoff.jpg",
          "about": { "ingredientsKey": "c38-ingredients" },
          "nutrition": { "calories": 380, "protein": "18g", "carbs": "32g" },
          "cookingKey": "c38-cook"
        },
        {
          "id": "c39",
          "name": "Kutaby",
          "descriptionKey": "c39-desc",
          "price": 6.00,
          "subgroup": "subgroup-main-courses",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/beefStroganoff.jpg",
          "about": { "ingredientsKey": "c39-ingredients" },
          "nutrition": { "calories": 290, "protein": "12g", "carbs": "32g" },
          "cookingKey": "c39-cook"
        },
        {
          "id": "c40",
          "name": "Potato Latkes (4 pc)",
          "descriptionKey": "c40-desc",
          "price": 6.00,
          "subgroup": "subgroup-main-courses",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/beefStroganoff.jpg",
          "about": { "ingredientsKey": "c40-ingredients" },
          "nutrition": { "calories": 180, "protein": "5g", "carbs": "22g" },
          "cookingKey": "c40-cook"
        }
      ]
    },
    {
      "id": "fresh",
      "titleKey": "section-fresh-title",
      "navLabelKey": "cat-fresh",
      "icon": "🥗",
      "scrollMargin": "scroll-mt-40",
      "products": [
        {
          "id": "f1",
          "name": "Aspic (Kholodets)",
          "descriptionKey": "f1-desc",
          "price": 16.00,
          "subgroup": "subgroup-cold-appetizers",
          "dietary": { "veg": false, "df": true, "pf": false },
          "image": "images/beefStroganoff.jpg",
          "about": { "ingredientsKey": "f1-ingredients" },
          "nutrition": { "calories": 200, "protein": "18g", "carbs": "3g" },
          "cookingKey": "f1-cook"
        },
        {
          "id": "f2",
          "name": "Gefilte Fish (4 pc)",
          "descriptionKey": "f2-desc",
          "price": 10.00,
          "subgroup": "subgroup-cold-appetizers",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/beefStroganoff.jpg",
          "about": { "ingredientsKey": "f2-ingredients" },
          "nutrition": { "calories": 180, "protein": "15g", "carbs": "8g" },
          "cookingKey": "f2-cook"
        },
        {
          "id": "f3",
          "name": "Gefilte Fish (8 pc)",
          "descriptionKey": "f3-desc",
          "price": 19.00,
          "subgroup": "subgroup-cold-appetizers",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/beefStroganoff.jpg",
          "about": { "ingredientsKey": "f3-ingredients" },
          "nutrition": { "calories": 180, "protein": "15g", "carbs": "8g" },
          "cookingKey": "f3-cook"
        },
        {
          "id": "f4",
          "name": "Babaganoush",
          "descriptionKey": "f4-desc",
          "price": 6.00,
          "unitKey": "per-12oz",
          "subgroup": "subgroup-salads",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "f4-ingredients" },
          "nutrition": { "calories": 120, "protein": "3g", "carbs": "10g" },
          "cookingKey": "f4-cook"
        },
        {
          "id": "f5",
          "name": "Beet Salad with Nuts",
          "descriptionKey": "f5-desc",
          "price": 6.00,
          "unitKey": "per-12oz",
          "subgroup": "subgroup-salads",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "f5-ingredients" },
          "nutrition": { "calories": 140, "protein": "3g", "carbs": "12g" },
          "cookingKey": "f5-cook"
        },
        {
          "id": "f6",
          "name": "Beet Salad with Sesame",
          "descriptionKey": "f6-desc",
          "price": 6.00,
          "unitKey": "per-12oz",
          "subgroup": "subgroup-salads",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "f6-ingredients" },
          "nutrition": { "calories": 130, "protein": "3g", "carbs": "11g" },
          "cookingKey": "f6-cook"
        },
        {
          "id": "f7",
          "name": "Korean Carrots",
          "descriptionKey": "f7-desc",
          "price": 6.00,
          "unitKey": "per-12oz",
          "subgroup": "subgroup-salads",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "f7-ingredients" },
          "nutrition": { "calories": 110, "protein": "1g", "carbs": "10g" },
          "cookingKey": "f7-cook"
        },
        {
          "id": "f8",
          "name": "Salted Cabbage",
          "descriptionKey": "f8-desc",
          "price": 6.00,
          "unitKey": "per-12oz",
          "subgroup": "subgroup-salads",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "f8-ingredients" },
          "nutrition": { "calories": 60, "protein": "2g", "carbs": "12g" },
          "cookingKey": "f8-cook"
        },
        {
          "id": "f9",
          "name": "Lecho Vegetable",
          "descriptionKey": "f9-desc",
          "price": 6.00,
          "unitKey": "per-12oz",
          "subgroup": "subgroup-salads",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "f9-ingredients" },
          "nutrition": { "calories": 90, "protein": "2g", "carbs": "12g" },
          "cookingKey": "f9-cook"
        },
        {
          "id": "f10",
          "name": "Georgian Salad",
          "descriptionKey": "f10-desc",
          "price": 6.00,
          "unitKey": "per-12oz",
          "subgroup": "subgroup-salads",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "f10-ingredients" },
          "nutrition": { "calories": 100, "protein": "3g", "carbs": "9g" },
          "cookingKey": "f10-cook"
        },
        {
          "id": "f11",
          "name": "Eggplant Sweet & Sour",
          "descriptionKey": "f11-desc",
          "price": 6.00,
          "unitKey": "per-12oz",
          "subgroup": "subgroup-salads",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "f11-ingredients" },
          "nutrition": { "calories": 130, "protein": "2g", "carbs": "14g" },
          "cookingKey": "f11-cook"
        },
        {
          "id": "f12",
          "name": "Eggplant with Tomatoes",
          "descriptionKey": "f12-desc",
          "price": 6.00,
          "unitKey": "per-12oz",
          "subgroup": "subgroup-salads",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "f12-ingredients" },
          "nutrition": { "calories": 110, "protein": "2g", "carbs": "11g" },
          "cookingKey": "f12-cook"
        },
        {
          "id": "f13",
          "name": "Mushroom Spread",
          "descriptionKey": "f13-desc",
          "price": 6.00,
          "unitKey": "per-12oz",
          "subgroup": "subgroup-salads",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "f13-ingredients" },
          "nutrition": { "calories": 90, "protein": "3g", "carbs": "8g" },
          "cookingKey": "f13-cook"
        },
        {
          "id": "f14",
          "name": "Liver Pâté",
          "descriptionKey": "f14-desc",
          "price": 6.00,
          "unitKey": "per-12oz",
          "subgroup": "subgroup-salads",
          "dietary": { "veg": false, "df": false, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "f14-ingredients" },
          "nutrition": { "calories": 200, "protein": "16g", "carbs": "5g" },
          "cookingKey": "f14-cook"
        },
        {
          "id": "f15",
          "name": "Herring Pâté",
          "descriptionKey": "f15-desc",
          "price": 6.00,
          "unitKey": "per-12oz",
          "subgroup": "subgroup-salads",
          "dietary": { "veg": false, "df": false, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "f15-ingredients" },
          "nutrition": { "calories": 180, "protein": "12g", "carbs": "6g" },
          "cookingKey": "f15-cook"
        },
        {
          "id": "f16",
          "name": "Beet & Potato Salad",
          "descriptionKey": "f16-desc",
          "price": 6.00,
          "unitKey": "per-12oz",
          "subgroup": "subgroup-salads",
          "dietary": { "veg": true, "df": true, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "f16-ingredients" },
          "nutrition": { "calories": 150, "protein": "3g", "carbs": "18g" },
          "cookingKey": "f16-cook"
        },
        {
          "id": "f17",
          "name": "Olivier Potato Salad",
          "descriptionKey": "f17-desc",
          "price": 6.00,
          "unitKey": "per-12oz",
          "subgroup": "subgroup-salads",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/perogies.jpg",
          "about": { "ingredientsKey": "f17-ingredients" },
          "nutrition": { "calories": 220, "protein": "5g", "carbs": "16g" },
          "cookingKey": "f17-cook"
        },
        {
          "id": "f18",
          "name": "Borscht",
          "descriptionKey": "f18-desc",
          "price": 8.00,
          "unitKey": "per-16oz",
          "subgroup": "subgroup-soups",
          "dietary": { "veg": false, "df": false, "pf": true },
          "image": "images/golubtsi.jpg",
          "about": { "ingredientsKey": "f18-ingredients" },
          "nutrition": { "calories": 180, "protein": "8g", "carbs": "20g" },
          "cookingKey": "f18-cook"
        },
        {
          "id": "f19",
          "name": "Split Pea Soup",
          "descriptionKey": "f19-desc",
          "price": 8.00,
          "unitKey": "per-16oz",
          "subgroup": "subgroup-soups",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/golubtsi.jpg",
          "about": { "ingredientsKey": "f19-ingredients" },
          "nutrition": { "calories": 200, "protein": "12g", "carbs": "28g" },
          "cookingKey": "f19-cook"
        },
        {
          "id": "f20",
          "name": "Meatball Soup",
          "descriptionKey": "f20-desc",
          "price": 8.00,
          "unitKey": "per-16oz",
          "subgroup": "subgroup-soups",
          "dietary": { "veg": false, "df": true, "pf": false },
          "image": "images/golubtsi.jpg",
          "about": { "ingredientsKey": "f20-ingredients" },
          "nutrition": { "calories": 190, "protein": "13g", "carbs": "16g" },
          "cookingKey": "f20-cook"
        },
        {
          "id": "f21",
          "name": "Cold Borscht",
          "descriptionKey": "f21-desc",
          "price": 8.00,
          "unitKey": "per-16oz",
          "subgroup": "subgroup-soups",
          "dietary": { "veg": true, "df": false, "pf": true },
          "image": "images/golubtsi.jpg",
          "about": { "ingredientsKey": "f21-ingredients" },
          "nutrition": { "calories": 120, "protein": "5g", "carbs": "15g" },
          "cookingKey": "f21-cook"
        },
        {
          "id": "f22",
          "name": "Green Borscht",
          "descriptionKey": "f22-desc",
          "price": 8.00,
          "unitKey": "per-16oz",
          "subgroup": "subgroup-soups",
          "dietary": { "veg": false, "df": false, "pf": true },
          "image": "images/golubtsi.jpg",
          "about": { "ingredientsKey": "f22-ingredients" },
          "nutrition": { "calories": 150, "protein": "7g", "carbs": "18g" },
          "cookingKey": "f22-cook"
        },
        {
          "id": "f23",
          "name": "Pilaf with Lamb",
          "descriptionKey": "f23-desc",
          "price": 14.00,
          "subgroup": "subgroup-main-courses",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/beefStroganoff.jpg",
          "about": { "ingredientsKey": "f23-ingredients" },
          "nutrition": { "calories": 480, "protein": "22g", "carbs": "52g" },
          "cookingKey": "f23-cook"
        }
      ]
    },
    {
      "id": "sauces",
      "titleKey": "section-sauces-title",
      "navLabelKey": "cat-sauces",
      "icon": "🔥",
      "scrollMargin": "scroll-mt-40",
      "products": [
        {
          "id": "s1",
          "name": "Beef Stroganoff",
          "descriptionKey": "s1-desc",
          "price": 10.00,
          "unitKey": "per-500ml",
          "dietary": { "veg": false, "df": false, "pf": true },
          "image": "images/beefStroganoff.jpg",
          "about": { "ingredientsKey": "s1-ingredients", "bestWithKey": "s1-bestwith" },
          "nutrition": { "calories": 380, "protein": "28g", "carbs": "8g" },
          "cookingKey": "s1-cook"
        },
        {
          "id": "s2",
          "name": "Creamy Chicken Mushroom",
          "descriptionKey": "s2-desc",
          "price": 10.00,
          "unitKey": "per-500ml",
          "dietary": { "veg": false, "df": false, "pf": true },
          "image": "images/beefStroganoff.jpg",
          "about": { "ingredientsKey": "s2-ingredients", "bestWithKey": "s2-bestwith" },
          "nutrition": { "calories": 410, "protein": "31g", "carbs": "5g" },
          "cookingKey": "s2-cook"
        },
        {
          "id": "s3",
          "name": "Navy Style",
          "descriptionKey": "s3-desc",
          "price": 10.00,
          "unitKey": "per-500ml",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/beefStroganoff.jpg",
          "about": { "ingredientsKey": "s3-ingredients", "bestWithKey": "s3-bestwith" },
          "nutrition": { "calories": 350, "protein": "20g", "carbs": "30g" },
          "cookingKey": "s3-cook"
        },
        {
          "id": "s4",
          "name": "Thai Green Chicken Curry",
          "descriptionKey": "s4-desc",
          "price": 10.00,
          "unitKey": "per-500ml",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/beefStroganoff.jpg",
          "about": { "ingredientsKey": "s4-ingredients", "bestWithKey": "s4-bestwith" },
          "nutrition": { "calories": 320, "protein": "24g", "carbs": "12g" },
          "cookingKey": "s4-cook"
        },
        {
          "id": "s5",
          "name": "Butter Chicken",
          "descriptionKey": "s5-desc",
          "price": 10.00,
          "unitKey": "per-500ml",
          "dietary": { "veg": false, "df": false, "pf": true },
          "image": "images/beefStroganoff.jpg",
          "about": { "ingredientsKey": "s5-ingredients", "bestWithKey": "s5-bestwith" },
          "nutrition": { "calories": 420, "protein": "25g", "carbs": "14g" },
          "cookingKey": "s5-cook"
        },
        {
          "id": "s6",
          "name": "Goulash",
          "descriptionKey": "s6-desc",
          "price": 10.00,
          "unitKey": "per-500ml",
          "dietary": { "veg": false, "df": true, "pf": true },
          "image": "images/beefStroganoff.jpg",
          "about": { "ingredientsKey": "s6-ingredients", "bestWithKey": "s6-bestwith" },
          "nutrition": { "calories": 340, "protein": "22g", "carbs": "15g" },
          "cookingKey": "s6-cook"
        }
      ]
    }
  ]
};
